### ISSUE TITLE
Suggestion: node install option

### ISSUE THREAD

**Issue by Viral-Inc** [vvo/gifify#102]
I think this "docker-gifify" package is worthy of being linked to as an option for drop-in Dockerfile dependency installation:

https://github.com/bcbcarl/docker-gifify/blob/master/Dockerfile

I kind of can't believe how easy it made getting gifify running in gcloud containers.

**Comment by vvo** [comment]
Hey there's also https://github.com/maxogden/gifify-docker, linked in the readme, maybe update the readme and add it to the top somewhere? Thanks
