### ISSUE TITLE
"TypeError: Cannot set property 'inputFilePath' of undefined"

### ISSUE THREAD

**Issue by bikowalczyk** [vvo/gifify#104]
Hello, I'm trying to create a node js app , which will first download a mp4 file, then convert it into gif.
The video file is created successfully, but when I begin to convert it, I get this error:

![image](https://user-images.githubusercontent.com/34490652/38163712-dc3b7efc-34f8-11e8-8072-19c854076856.png)

This is my node js code: 
```
app.get('/gif', function(req, res){
    const link = (JSON.stringify(req.query.url).slice(1,-1));   //direct mp4 link

    //now download file locally, send download url and destroy file
    const fileName = link.slice(-14);  
    const r = request(link);

    r.on('response', (resp)=>{
    const stream = resp.pipe(fs.createWriteStream(__dirname + '/downloads/' + fileName));
    stream.on('finish',()=> gifify(__dirname + '/downloads/' + fileName).pipe(__dirname + '/downloads/' + fileName.slice(1,-4) +'.gif'));
    }); 

})

```

Do you know what may cause the issue? 

Thanks ;)

**Comment by vvo** [comment]
just published a new version, try it
