### ISSUE TITLE
How to convert sequence of PNGs

### ISSUE THREAD

**Issue by hyperknot** [vvo/gifify#106]
I'd like to convert a sequence of PNG files, showing each for 2 seconds. 
I prefer not to export to an mp4 file temporarily, as that'd ruin quality. 

How is it possible to do this in gifify in the best possible quality?

**Comment by vvo** [comment]
I think you will have more chances just using ffmpeg, search for your question on google or stackoverflow.

gifify goal is to turn mp4 into gifs that's it.

thanks!
