### ISSUE TITLE
MacOS Mojave: Brew prepends libtool with a "g" and breaks gifify

### ISSUE THREAD

**Issue by heyheni** [vvo/gifify#109]
Hi thank you for creating gifify!
When i was installing gifify I was greeted with this message.

> libtool
> In order to prevent conflicts with Apple's own libtool we have prepended a "g"
> so, you have instead: glibtool and glibtoolize.

after that the result was that gifify did't work

> Could not find gifsicle. Is it installed?
> More info: https://github.com/vvo/gifify#requirements

Thank you for resolving this.

**Comment by vvo** [comment]
@heyheni could you submit a PR to solve this? You should be able to check that we are on a specific version of macos using nodejs process api

**Comment by hyperknot** [comment]
Don't use homebrew to install gifify, that formula is broken. Simply install it with node and it'll work nicely, based on what's written in the readme.
