### ISSUE TITLE
gifify not working after installation!

### ISSUE THREAD

**Issue by fabianod** [vvo/gifify#11]
I'm using Ubuntu 14.04 64 bits and after install all dependencies and gifify, de program is not working!

By not working I mean, when I type gifify <ENTER> it returns nothing. And the same thing happens when I use a real command line, trying to convert a file.

This behavior started after the installation of the module node, before this procedure, my attempts to run the program resulted in a error message ( "/usr/bin/env: node: File or folder not found").

I'll add bellow some informations of the installed programs in my system.

Thanks!

ffmpeg version 2.5.2 Copyright (c) 2000-2014 the FFmpeg developers
built on Dec 25 2014 00:04:42 with gcc 4.8 (Ubuntu 4.8.2-19ubuntu1)

Version: ImageMagick 6.7.7-10 2014-03-06 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2012 ImageMagick Studio LLC
Features: OpenMP    

LCDF Gifsicle 1.82
Copyright (C) 1997-2014 Eddie Kohler
This is free software; see the source for copying conditions.
There is NO warranty, not even for merchantability or fitness for a
particular purpose.

$ sudo npm install -g gifify

npm http GET https://registry.npmjs.org/gifify
npm http 304 https://registry.npmjs.org/gifify
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/moment-duration-format
npm http GET https://registry.npmjs.org/moment
npm http GET https://registry.npmjs.org/promise
npm http GET https://registry.npmjs.org/whereis
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/moment
npm http 304 https://registry.npmjs.org/promise
npm http 304 https://registry.npmjs.org/moment-duration-format
npm http 304 https://registry.npmjs.org/whereis
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/asap
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/asap
/usr/local/bin/gifify -> /usr/local/lib/node_modules/gifify/bin/gifify
gifify@2.0.0 /usr/local/lib/node_modules/gifify
├── whereis@0.4.0
├── commander@2.6.0
├── moment-duration-format@1.3.0
├── moment@2.8.4
├── debug@2.1.1 (ms@0.6.2)
└── promise@6.0.1 (asap@1.0.0)

**Comment by norpol** [comment]
Looks like a 'fuck up' with your environment variables, or your nodejs installation. Do you've got an execute-able file under `/usr/bin/node` if not you can also type on your CLI `which node`, this will look-up if node is somewhere else?
Try also `apt-get install nodejs-legacy`.
More details are also here https://github.com/atom/atom/issues/2025 .

**Comment by fabianod** [comment]
Tried to re-install the nodejs module with no sucess, but after installing the nodejs-legacy it worked like a charm!

Thank you very much!
