### ISSUE TITLE
Homebrew removed formula options

### ISSUE THREAD

**Issue by keepitcomplicated** [vvo/gifify#112]
Since I can't instally anything with options through homebrew, does anyone have a solution to keep gifify working?

**Comment by datou0412** [comment]
brew install ffmpeg --with-libass --with-fontconfig no longer works

Error: invalid option: --with-libass

**Comment by Zantier** [comment]
If you're not adding text to the gif, a workaround is to install the packages without the options, and then modify gifify to remove a requirement on the `convert` command from imagemagick.

```
brew install node
brew install ffmpeg
brew install imagemagick
brew install giflossy
npm install -g gifify
```

(With version 2.4.2 of gifify) Comment out line 101 of `/usr/local/lib/node_modules/gifify/bin/gifify`:

```
  if(process.platform !== 'win32') {
    //required.push({'bin': 'convert', 'args': '--version', 'needs': ['fontconfig']});
  } else {
```

I assume this will be overwritten if you ever update the package.

**Comment by hyperknot** [comment]
Thanks @Zantier for the update. I think we should make a PR about it, if the project is unmaintained at least it should install on recent homebrew. 

@vvo would you accept a PR with that line commented out, so that it can continue to work on macOS?

**Comment by vvo** [comment]
> @vvo would you accept a PR with that line commented out, so that it can continue to work on macOS?

Yes please do and Ill release, anyone willing to maintain this?

**Comment by hyperknot** [comment]
@vvo I've submitted two PRs regarding the homebrew update.

I think this tool is working really nicely, does it really need that much maintenance? I mean it's an offline command line tool, calling external applications, there isn't any security risk like on a web server. I think if you only do maintenance releases occasionally and no new features, it can work for the foreseeable future, wouldn't it?

**Comment by vvo** [comment]
yes yes, just I am not watching this repository, thus if you need me to do something, ping @vvo :)

**Comment by vvo** [comment]
> I think this tool is working really nicely
Thanks for that :)
