### ISSUE TITLE
--from and --to not correctly creating the gif to the desired time

### ISSUE THREAD

**Issue by Mark117** [vvo/gifify#116]
I am trying to create a gif using the `--from` and `--to` options. For demonstration purposes, I'm creating a gif that should be 1 second long. 

My command is `gifify movie.mp4 -o movie1.gif --from 33 --to 34 --resize 500:-1`. The problem is that regardless of the time that I specify, I'm always getting a 25-second gif

I have also tried using the full `hh:mm:ss` timestamp and the video length is still the same. Am I using the command line incorrectly?

The below commands also produce the same 25-sec output:
`gifify movie.mp4 -o movie2.gif --from 00:00:33 --to 00:00:34 --resize 500:-1`
`gifify movie.mp4 -o movie1.gif --from 00:00:33.000 --to 00:00:34.000 --resize 500:-1`

**Comment by vvo** [comment]
weird, best option would be to 1. cut the video yourself for example with https://online-video-cutter.com/ and then use gifify and see how it goes.

if you're just looking for easy to use desktop tools, maybe https://github.com/sindresorhus/Gifski would be easier nowadays, good luck!

**Comment by Mark117** [comment]
Thanks very much for the response. I figure this might have been an issue with an update to FFmpeg. I have run the FFmpeg commands directly and the video is correctly trimmed to the time.
