### ISSUE TITLE
"--lossy=80,--colors 80,..." - unrecognized  

### ISSUE THREAD

**Issue by mentierd** [vvo/gifify#13]
There is clearly an issue with the latest gifsicle build.  It turns out that the --lossy and --colors are no longer supported in the cli.  I found that the issue for gifify resides in index.js @ ln# 165. Not sure why you would publish a wrapper library that is suppose to support a forked version of gifsicle. Be more clear in your documentation.

function computeGifsicleArgs(opts) {
  // Gifsicle options
  // http://www.lcdf.org/gifsicle/man.html
  // --lossy is not yet into master, https://github.com/kohler/gifsicle/pull/16
  var args = [
      '-O3',
      '--lossy ' + opts.compress * 2,
      '--colors ' + opts.colors,
      '--no-warnings'
  ];

**Comment by vvo** [comment]
Hi @mentierd it's written in the readme that you should install giflossy: https://github.com/vvo/gifify/blob/master/README.md#requirements
