### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zwhitchcox** [vvo/gifify#15]
I get this error
```sh
gifsicle: unrecognized option ‘--lossy=80’
Usage: gifsicle [OPTION | FILE | FRAME]...
Try 'gifsicle --help' for more information.
```
whenever I try to use this.

I installed all the dependencies.

**Comment by vvo** [comment]
you need giflossy as stated in the readme

**Comment by zwhitchcox** [comment]
I installed giflossy

**Comment by zwhitchcox** [comment]
Nevermind, I got it

**Comment by vvo** [comment]
where in the readme?

**Comment by zwhitchcox** [comment]
Other than that though, it works great! Good job

**Comment by vvo** [comment]
coooool! nice!
