### ISSUE TITLE
keep getting an error

### ISSUE THREAD

**Issue by asafg84** [vvo/gifify#17]
Hi,
I keep getting this error when using gifify:

events.js:53
EventEmitter.prototype.emit = function emit(type) {
                                           ^
RangeError: Maximum call stack size exceeded

I'm running your get started example.

I think it has to do with the ffmpeg module dependency because when im trying to convert via shell I also get an error:

$ gifify inputs/mov.webm -o outputs/mov.gif --resize 800:-1
[Error: Could not find ffmpeg on your system]

Which is odd because i installed ffmpeg and I can require it.

How can i make it work?

Thank You!

**Comment by vvo** [comment]
asaf can you provide me with:
- the JavaScript code you are using which use the gifify API
- the video file your are trying to convert to GIF

So that I can reproduce your problem, thanks

**Comment by asafg84** [comment]
Sure,

js code

var fs = require('fs');
var gifify = require('gifify');
var path = require('path'),
    input_path = './uploads',
    output_path = './outputs';

var input = path.join(input_path, 'toGif.webm');
var output = path.join(output_path, 'toGif.gif');

var gif = fs.createWriteStream(output);

var options = {
    resize: '200:-1',
    from: 30,
    to: 35
};
 
gifify(input, options).pipe(gif);

console.log('done!');

The video im trying to convert is a 3s webm format. I can run it so its not corrupt.

Thanks!

**Comment by vvo** [comment]
Can you upload it somewhere still?

**Comment by asafg84** [comment]
https://drive.google.com/file/d/0B1aznL_n6b7EYWoxRzdHem9SeTg/view?usp=sharing

**Comment by Nikolaibibo** [comment]
experiencing the same issue with the same code on Mac OSX

**Comment by sbsomya** [comment]
I am also experiencing similar error

**Comment by MJunghenn** [comment]
+1

**Comment by vvo** [comment]
@asafg84 and everyone here, I was able to put your video into a GIF. So if some videos are not working, check all the requirements and install instructions, test another simple mp4 video, and in last resort: open a new issue, drop your video link and I will try it.
