### ISSUE TITLE
gifsicle: unrecognized option ‘--lossy=80’

### ISSUE THREAD

**Issue by ttback** [vvo/gifify#18]
just trying to run a simple `gifify vid.mp4 -o screencast.gif and ran into
````
gifsicle: unrecognized option ‘--lossy=80’
Usage: gifsicle [OPTION | FILE | FRAME]...
````
Not sure why...

**Comment by vvo** [comment]
You need giflossy: https://github.com/vvo/gifify#requirements

have fun

**Comment by ttback** [comment]
@vvo Thanks. :)
