### ISSUE TITLE
weird gif output

### ISSUE THREAD

**Issue by maxogden** [vvo/gifify#19]
using:

- yosemite
- gifsicle-1.82.1-lossy (from [here](https://github.com/pornel/giflossy/releases/tag/lossy%2F1.82.1))
- ffmpeg version 2.1.4 (from brew)
- ImageMagick 6.9.0-3 Q16 x86_64 2015-01-09 (from brew)

here's what I get from a .mov recorded with Quicktime:

```sh
gifify recording.mov -o recording.gif
```
![recording mov](https://cloud.githubusercontent.com/assets/39759/6220639/9930a282-b5ed-11e4-95c2-be6460005d53.gif)

**Comment by vvo** [comment]
Hi @maxogden, so you are not happy with the output scaling I guess?

Can you send me the .mov so I can test for myself? Thanks

**Comment by maxogden** [comment]
@vvo here ya go: http://max.ic.ht/dropbox/bucket/recording.mov

that .mov is created from the builtin Quicktime Player > File > New Screen Recording

**Comment by vvo** [comment]
I am a linux guy, talk to me about quicktime I will talk to you about realplayer ![](http://images.br.sftcdn.net/br/scrn/24000/24601/realplayer-11.jpg).

Looking at your issue.

**Comment by maxogden** [comment]
AHHH SORRY I am stupid. I had the [original gifify](https://gist.github.com/SlexAxton/4989674#file-zshrc) in my .bash_profile and it was getting used instead.

Using your gifify results in this which looks great:

![recording-node](https://cloud.githubusercontent.com/assets/39759/6220859/5bc419bc-b5f0-11e4-899d-8436c4042c52.gif)

**Comment by vvo** [comment]
This is what I got:

![recording](https://cloud.githubusercontent.com/assets/123822/6220864/d5f261d0-b63b-11e4-827f-368e79eed252.gif)

**Comment by vvo** [comment]
NO NO REOPEN! I WANT TO START A LINUX-OSX WAR!!

**Comment by vvo** [comment]
Glad my script solved your problems, have fun gififying.

please @maxogden sell my shit on twitter!

**Comment by maxogden** [comment]
has anyone made a Docker container for this yet? If not I will

**Comment by vvo** [comment]
oww you mean a runnable docker container exposing a binary? that would be cool indeed. MAKE IT HAPPEN!

**Comment by maxogden** [comment]
@vvo alright here ya go https://github.com/maxogden/gifify-docker
