### ISSUE TITLE
--fps doesn't take the input fps into account

### ISSUE THREAD

**Issue by kirbysayshi** [vvo/gifify#21]
If I have a .mov file recorded via quicktime, which records at 60fps, and use gifify, it creates a gif at 10fps. If I run gifify with `--fps 60`, it creates a gif 10x as long as the video, but slowed down.

Adding `--speed 6` seems to have no effect.

I assumed that `--fps` controlled the output fps, but had no effect on how often the frames were sampled. Is there a way to do what I'm trying to do using gifify?

**Comment by vvo** [comment]
speed now working
