### ISSUE TITLE
convert needs fontconfig

### ISSUE THREAD

**Issue by bfred-it** [vvo/gifify#27]
I see this error when I try to use gifify on my OS X 10.10

    convert needs fontconfig

I have imagemagick installed via homebrew:

    imagemagick: stable 6.9.0-9 (bottled), HEAD
    …
    ==> Dependencies
    …
    Optional: fontconfig ✔, …

And also

    $ brew install fontconfig
    Warning: fontconfig-2.11.1 already installed

What am I missing?

**Comment by vvo** [comment]
what's the output of `convert --version`?

**Comment by bfred-it** [comment]
```
Version: ImageMagick 6.9.0-3 Q16 x86_64 2015-01-09 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
Features: DPC Modules
Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png xml zlib
```

**Comment by vvo** [comment]
> Delegates (built-in): bzlib freetype jng jpeg ltdl lzma png xml zlib

It seems that your convert is missing builtin fontconfig, we check for it while trying `convert --version`.

Maybe we should check for `fontconfig` binary, what do you think?

**Comment by vvo** [comment]
Can you help @pjaspers?

**Comment by bfred-it** [comment]
My mistake, I guess! I removed imagemagick and reinstalled with the explicit option:

    $ brew install imagemagick --with-fontconfig

    $ convert --version
    Version: ImageMagick 6.9.1-4 Q16 x86_64 2015-06-04 http://www.imagemagick.org
    Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
    License: http://www.imagemagick.org/script/license.php
    Features:  Cipher DPC Modules
    Delegates (built-in): bzlib fontconfig freetype jng jpeg ltdl lzma png tiff webp xml zlib

**Comment by KevinWang2025** [comment]
How to  --with-fontconfig use in centos 7?
