### ISSUE TITLE
ffmpeg needs libass, fontconfig

### ISSUE THREAD

**Issue by OliverJAsh** [vvo/gifify#28]
How come I get this error? Do I need a different brew install formula?

**Comment by OliverJAsh** [comment]
Fixed with `brew install ffmpeg --with-fontconfig --with-libass`

**Comment by 3raxton** [comment]
When I get this issue Terminal comes back with: 
```
Warning: ffmpeg-3.2.4 already installed
``` 
What do I do in this case?

**Comment by vvo** [comment]
You should first remove it then reinstall. `brew uninstall ffmepg` should do it

**Comment by juan-cortes** [comment]
*ffmpeg

**Comment by BryanSharp** [comment]
Error: bison: undefined method `uses_from_macos' for #<Class:0x0000000101c1ff78>
