### ISSUE TITLE
Problems creating image

### ISSUE THREAD

**Issue by lcjury** [vvo/gifify#67]
I'm trying to convert part of .mp4 file but I get the following error:

convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.
convert: no images defined`gif:-' @ error/convert.c/ConvertImageCommand/3257.

Reinstalled everything from the readme but still getting the same error message, any advice?

**Comment by vvo** [comment]
Could you link me the mp4 video so I can try it? Thanks

**Comment by jblamber** [comment]
I received this error when I tried to turn a segment of a movie that didnt exist into a gif. For example, in a 5 second video, asking to convert seconds 30-35 into a gif. The app would crash with this error.
