### ISSUE TITLE
how to compress

### ISSUE THREAD

**Issue by okfirelee** [vvo/gifify#77]
i need a simple ex thx

**Comment by okfirelee** [comment]
compress gif size      50M to 20 or 2M

**Comment by vvo** [comment]
Hi, I am sorry I could not understand what is your issue right now. Can you add more context, longer sentences and an actual question? Thanks.

**Comment by okfirelee** [comment]
I would like to put a GIF image file by the size of 50M compressed to 30M or smaller

**Comment by vvo** [comment]
Hi @okfirelee, this repository is a project to generate GIFS from mp4, you may try google for optimizing GIFS, or stackoverflow. I am sorry but your issue description is too small to be able to help you here. Good luck
