### ISSUE TITLE
gifify is hanging the computer while converting even small video files

### ISSUE THREAD

**Issue by karuppiah7890** [vvo/gifify#97]
My computer literally hangs while trying to convert 10 seconds of a 5 MB video to GIF. And sometimes it takes too long to convert it into a GIF, but it does finally. And my computer has 4 GB RAM

**Comment by vvo** [comment]
I am sorry yes I do also find the processing to be REALLY HEAVY, I don't know how to solve that ultimately.

**Comment by fogine** [comment]
Well, at the current state it's unusable. While converting 800k 60sec mp4 it eats all 16GB of available RAM... and without swap it crashes right after...

**Comment by pixelastic** [comment]
I've recently installed `gifify` on a new laptop, and I can confirm it hangs even for short recordings, and freezes my whole laptop, forcing me to a hard reboot.

The only difference I can think of is the version of ffmpeg installed that is newer on this laptop, but I don't know how I could fix it.

As a workaround, I've re-implemented the gifify logic I needed with commandline tools: `ffmpeg` to convert a video into a set of still `png` files, `convert` to convert those files into a `gif` and `gifsicle` (the pornel fork) to compress it. Results are similar to what `gifify` was doing, but I lost the easy to use API and some other features.

**Comment by vvo** [comment]
There might be a flag used in gifify that is triggering this indeed. Long time I used gifify. I just use gifox when recording which have very good results: https://gifox.io/

Do try to change some flags if you want gifify speed back, let us know!
