### ISSUE TITLE
convert-im6.q16: cache resources exhausted 

### ISSUE THREAD

**Issue by arthurlutz** [vvo/gifify#99]
On some video files (not all) I get the follow error and the produced file is empty : 

```
$ gifify --colors 255 -o x.gif --resize '800:-1' VID_20170820_124826.mp4
convert-im6.q16: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/244.
convert-im6.q16: cache resources exhausted `/tmp/magick-22271zppvVjFkR5gk' @ error/cache.c/OpenPixelCache/3945.
$ file x.gif 
x.gif: empty
$ file VID_20170820_124826.mp4
VID_20170820_124826.mp4: ISO Media, MPEG v4 system, 3GPP
$ dpkg -l ffmpeg
ii  ffmpeg                 7:3.2.4-1build2  amd64            Tools for transcoding, streaming and playing of m
$ dpkg -l imagemagick
ii  imagemagick            8:6.9.7.4+dfsg-3 amd64            image manipulation programs -- binaries
```

**Comment by arthurlutz** [comment]
The video was 30 seconds long, I ended up doing three runs of 10 seconds and that works...

**Comment by fatso83** [comment]
Same problem. Tried making a gif out of a 45 second gif. Both this and the following script ends with the same error:
```
$ ffmpeg -i demo.mp4 -r 10 -f image2pipe -vcodec ppm - |   convert -delay 5 -loop 0 - output.gif

convert-im6.q16: DistributedPixelCache '127.0.0.1' @ error/distribute-cache.c/ConnectPixelCacheServer/244.
convert-im6.q16: cache resources exhausted `/tmp/magick-11492-FwYUnivxewm' @ error/cache.c/OpenPixelCache/3982.
convert-im6.q16: no images defined `gif:-' @ error/convert.c/ConvertImageCommand/3258.
```

**Comment by ianzitow** [comment]
Try this: https://github.com/ImageMagick/ImageMagick/issues/396

**Comment by AlexandreBonneau** [comment]
It seems that issue could be closed, since the workaround described in #396 works great (ie. increasing the available memory in the `/etc/ImageMagick-6/policy.xml` file).

**Comment by vvo** [comment]
Hey @AlexandreBonneau, can you give a link to the workaround? thanks!

**Comment by AlexandreBonneau** [comment]
@vvo I was referring to the issue #396 mentioned just above. I edited my comment to add the link.

**Comment by vvo** [comment]
Thanks, for anyone following this, here's the workaround: https://github.com/ImageMagick/ImageMagick/issues/396#issuecomment-319569255
